---

server.port: 9090
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qadb
    username: "root"
    password: root
spring.jpa:
    show_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: create
